---
- name: Provision resources in Azure
  hosts: localhost
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        location: "{{ location }}"
        name: "{{ public_ip_name }}"
        sku: Standard
        version: ipv4
        allocation_method: Static
        state: present
        tags: "{{ tags }}"
      register: output_ip_address

    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."
