---
- name: Provision resources in Azure
  hosts: localhost
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        location: "{{ location }}"
        name: "{{ virtual_machine_name }}"
        os_type: Linux
        vm_size: Standard_DS2_v2
        managed_disk_type: Standard_LRS
        short_hostname: "{{ username }}PC01"
        admin_username: "{{ username }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/"{{ username }}"/.ssh/authorized_keys
            key_data: "{{ ssh_key_data }}"
        network_interfaces: "{{ network_interface_name }}"
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: '22_04-lts-gen2'
          version: latest
        state: present
        tags: "{{ tags }}"